# Generated by Django 4.1 on 2022-12-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgmodel',
            old_name='img',
            new_name='select_a_meme',
        ),
    ]
