# Generated by Django 4.1 on 2022-12-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_img_imgmodel_select_a_meme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgmodel',
            old_name='select_a_meme',
            new_name='img',
        ),
    ]
